import { useTranslations } from 'next-intl'
import { Metadata } from 'next'

import { Form } from '@/components/form'
import { Toolbar } from '@/components/toolbar'
import { resolvePackage } from '@/services/package'

export const metadata: Metadata = {
  title: 'HOME - Gratia',
  description: 'Generated by create next app',
}

const { homepage } = resolvePackage()

export default function Home() {
  const t = useTranslations()

  return (
    <>
      <div className="icon-[carbon--continuous-integration] inline-block text-5xl" />
      <p>
        <a rel="noreferrer" href={homepage} target="_blank"> Gratia </a>
      </p>
      <p><em className="text-sm opacity-75">{t('intro.desc')}</em></p>
      <div className="py-4"></div>
      
      <Form />

      <Toolbar />
    </>
  )
}
