import { useTranslations } from 'next-intl'
import { Metadata } from 'next'

import { Form } from '@/components/form'
import { Toolbar } from '@/components/toolbar'

export const metadata: Metadata = {
  title: 'HOME - Starter NextJS',
  description: 'Generated by create next app',
}

export default function Home() {
  const t = useTranslations()

  return (
    <>
      <div className="icon-[carbon--campsite] inline-block text-5xl" />
      <p>
        <a rel="noreferrer" href="https://github.com/clovu/tarter-nextjs" target="_blank"> Starter </a>
      </p>
      <p><em className="text-sm opacity-75">{t('intro.desc')}</em></p>
      <div className="py-4"></div>
      
      <Form />

      <Toolbar />
    </>
  )
}
